version: '3'

services:
  frontend:
    build:
      context: ./frontend/
    command: cp -r /app/build/. /static/
    ports:
      - "3000:3000"
    volumes:
      - static:/static

volumes:
  static:
