version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - static:/backend_static
      - backend:/app/media/
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend

  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["poetry", "run", "daphne", "-b", "0.0.0.0", "-p", "8001", "backend.wsgi:application"]
    depends_on:
      - backend
    ports:
      - "8001:8001"

  redis:
    image: redis
    container_name: redis
    command:
      - redis-server
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - db

volumes:
  static:
  media:
  backend:
  pg_data:
